apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app: segundo-pod
spec:
  containers:
    - name: container-pod-2
      image: mysql:8.0
      ports:
        - containerPort: 3306
      env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: 1q2w3e4r2021
        - name: "MYSQL_DATABASE"
          value: kubernetes
        - name: "MYSQL_PASSWORD"
          value: 1q2w3e4r