apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-02
spec:
  template:
    metadata:
      name: replicaset-02
      labels:
        app: replicaset-02
    spec:
      containers:
        - name: container-pod-2
          image: mysql:8.0
          ports:
            - containerPort: 3306
  replicas: 3
  selector:
    matchLabels:
      app: replicaset-02